/* =====================================================================
   MDPH Assist — base médicaments locale (hors-ligne)
   Autocomplétion dès 3 lettres (nom DCI ou classe) + effet secondaire
   principal. AIDE À LA RÉDACTION — à vérifier (RCP/Vidal/ANSM).
   Format : {n:nom DCI, c:classe, es:effet secondaire principal}
   ===================================================================== */
'use strict';
window.MEDS = [
  /* --- Cardio-vasculaire : antihypertenseurs --- */
  {n:"Ramipril",c:"IEC (antihypertenseur)",es:"toux sèche, hyperkaliémie, hypotension"},
  {n:"Périndopril",c:"IEC (antihypertenseur)",es:"toux sèche, hyperkaliémie"},
  {n:"Énalapril",c:"IEC (antihypertenseur)",es:"toux sèche, insuffisance rénale fonctionnelle"},
  {n:"Lisinopril",c:"IEC (antihypertenseur)",es:"toux sèche, angio-œdème (rare)"},
  {n:"Losartan",c:"ARA II (sartan)",es:"hyperkaliémie, vertiges"},
  {n:"Valsartan",c:"ARA II (sartan)",es:"hyperkaliémie, hypotension"},
  {n:"Candésartan",c:"ARA II (sartan)",es:"hyperkaliémie, asthénie"},
  {n:"Irbésartan",c:"ARA II (sartan)",es:"hyperkaliémie, sensations vertigineuses"},
  {n:"Amlodipine",c:"Inhibiteur calcique",es:"œdèmes des membres inférieurs, céphalées"},
  {n:"Lercanidipine",c:"Inhibiteur calcique",es:"œdèmes des chevilles, bouffées vasomotrices"},
  {n:"Bisoprolol",c:"Bêtabloquant",es:"bradycardie, asthénie, refroidissement des extrémités"},
  {n:"Aténolol",c:"Bêtabloquant",es:"bradycardie, fatigue, bronchospasme"},
  {n:"Nébivolol",c:"Bêtabloquant",es:"bradycardie, céphalées, fatigue"},
  {n:"Métoprolol",c:"Bêtabloquant",es:"bradycardie, hypotension, fatigue"},
  {n:"Furosémide",c:"Diurétique de l'anse",es:"hypokaliémie, déshydratation, hypotension"},
  {n:"Hydrochlorothiazide",c:"Diurétique thiazidique",es:"hyponatrémie, hypokaliémie, hyperuricémie"},
  {n:"Indapamide",c:"Diurétique thiazidique",es:"hypokaliémie, hyponatrémie"},
  {n:"Spironolactone",c:"Diurétique épargneur de potassium",es:"hyperkaliémie, gynécomastie"},
  /* --- Cardio : anti-ischémique / rythme / anticoagulant --- */
  {n:"Trinitrine",c:"Dérivé nitré",es:"céphalées, hypotension orthostatique"},
  {n:"Molsidomine",c:"Vasodilatateur (angor)",es:"céphalées, hypotension"},
  {n:"Amiodarone",c:"Antiarythmique",es:"dysthyroïdie, photosensibilité, dépôts cornéens"},
  {n:"Flécaïnide",c:"Antiarythmique",es:"troubles visuels, effet pro-arythmogène"},
  {n:"Digoxine",c:"Tonicardiaque (digitalique)",es:"troubles digestifs, troubles du rythme (surdosage)"},
  {n:"Ivabradine",c:"Ralentisseur du nœud sinusal",es:"phosphènes, bradycardie"},
  {n:"Aspirine",c:"Antiagrégant plaquettaire",es:"saignement digestif, gastralgies"},
  {n:"Clopidogrel",c:"Antiagrégant plaquettaire",es:"saignement, ecchymoses"},
  {n:"Ticagrélor",c:"Antiagrégant plaquettaire",es:"saignement, dyspnée"},
  {n:"Apixaban",c:"Anticoagulant oral direct",es:"hémorragie, anémie"},
  {n:"Rivaroxaban",c:"Anticoagulant oral direct",es:"hémorragie"},
  {n:"Dabigatran",c:"Anticoagulant oral direct",es:"hémorragie, dyspepsie"},
  {n:"Warfarine",c:"Antivitamine K",es:"hémorragie (surveillance INR)"},
  {n:"Fluindione",c:"Antivitamine K",es:"hémorragie, allergie/immuno-allergie"},
  {n:"Énoxaparine",c:"Héparine de bas poids moléculaire",es:"hémorragie, thrombopénie (TIH)"},
  /* --- Hypolipémiants --- */
  {n:"Atorvastatine",c:"Statine",es:"myalgies, élévation des transaminases"},
  {n:"Rosuvastatine",c:"Statine",es:"myalgies, troubles digestifs"},
  {n:"Simvastatine",c:"Statine",es:"myalgies, crampes"},
  {n:"Pravastatine",c:"Statine",es:"myalgies, troubles digestifs"},
  {n:"Ézétimibe",c:"Hypolipémiant (inhibiteur absorption)",es:"diarrhée, myalgies"},
  {n:"Fénofibrate",c:"Fibrate",es:"myalgies, troubles digestifs"},
  /* --- Diabète --- */
  {n:"Metformine",c:"Antidiabétique (biguanide)",es:"troubles digestifs, diarrhée"},
  {n:"Gliclazide",c:"Sulfamide hypoglycémiant",es:"hypoglycémie, prise de poids"},
  {n:"Glimépiride",c:"Sulfamide hypoglycémiant",es:"hypoglycémie"},
  {n:"Sitagliptine",c:"Antidiabétique (gliptine)",es:"troubles digestifs, rares pancréatites"},
  {n:"Empagliflozine",c:"Antidiabétique (iSGLT2)",es:"infections génito-urinaires, déshydratation"},
  {n:"Dapagliflozine",c:"Antidiabétique (iSGLT2)",es:"mycoses génitales, polyurie"},
  {n:"Liraglutide",c:"Analogue du GLP-1",es:"nausées, troubles digestifs"},
  {n:"Sémaglutide",c:"Analogue du GLP-1",es:"nausées, vomissements"},
  {n:"Insuline",c:"Insulinothérapie",es:"hypoglycémie, prise de poids"},
  {n:"Lévothyroxine",c:"Hormone thyroïdienne",es:"palpitations/tachycardie si surdosage"},
  /* --- Respiratoire --- */
  {n:"Salbutamol",c:"Bêta-2 mimétique de courte durée",es:"tremblements, tachycardie, palpitations"},
  {n:"Terbutaline",c:"Bêta-2 mimétique de courte durée",es:"tremblements, tachycardie"},
  {n:"Formotérol",c:"Bêta-2 mimétique de longue durée",es:"tremblements, crampes"},
  {n:"Salmétérol",c:"Bêta-2 mimétique de longue durée",es:"tremblements, céphalées"},
  {n:"Tiotropium",c:"Anticholinergique inhalé (BPCO)",es:"sécheresse buccale, rétention urinaire"},
  {n:"Ipratropium",c:"Anticholinergique inhalé",es:"sécheresse buccale, toux"},
  {n:"Budésonide",c:"Corticoïde inhalé",es:"candidose oropharyngée, dysphonie"},
  {n:"Fluticasone",c:"Corticoïde inhalé",es:"candidose orale, raucité de la voix"},
  {n:"Béclométasone",c:"Corticoïde inhalé",es:"candidose orale, dysphonie"},
  {n:"Montélukast",c:"Antileucotriène",es:"troubles neuropsychiatriques, céphalées"},
  {n:"Théophylline",c:"Bronchodilatateur (xanthine)",es:"tachycardie, nausées, insomnie"},
  /* --- Corticoïdes & immunomodulateurs --- */
  {n:"Prednisone",c:"Corticoïde oral",es:"ostéoporose, diabète, HTA, prise de poids"},
  {n:"Prednisolone",c:"Corticoïde oral",es:"ostéoporose, fragilité cutanée, insomnie"},
  {n:"Méthotrexate",c:"Immunosuppresseur / DMARD",es:"cytopénies, hépatotoxicité, pneumopathie"},
  {n:"Hydroxychloroquine",c:"Antipaludéen de synthèse (rhumato)",es:"rétinopathie, troubles digestifs"},
  {n:"Léflunomide",c:"DMARD",es:"diarrhée, HTA, hépatotoxicité"},
  {n:"Sulfasalazine",c:"DMARD / MICI",es:"troubles digestifs, cytopénies"},
  {n:"Azathioprine",c:"Immunosuppresseur",es:"cytopénies, troubles digestifs"},
  {n:"Adalimumab",c:"Biothérapie anti-TNFα",es:"infections, réactions au point d'injection"},
  {n:"Étanercept",c:"Biothérapie anti-TNFα",es:"infections, réactions locales"},
  {n:"Infliximab",c:"Biothérapie anti-TNFα",es:"infections, réactions à la perfusion"},
  {n:"Védolizumab",c:"Biothérapie (MICI)",es:"infections, arthralgies"},
  {n:"Rituximab",c:"Biothérapie anti-CD20",es:"infections, réactions à la perfusion"},
  {n:"Ocrélizumab",c:"Biothérapie (SEP)",es:"infections, réactions à la perfusion"},
  {n:"Mycophénolate",c:"Immunosuppresseur (greffe)",es:"troubles digestifs, cytopénies, infections"},
  {n:"Tacrolimus",c:"Immunosuppresseur (greffe)",es:"néphrotoxicité, tremblements, diabète"},
  {n:"Ciclosporine",c:"Immunosuppresseur (greffe)",es:"néphrotoxicité, HTA, hypertrophie gingivale"},
  /* --- Neurologie --- */
  {n:"Lévodopa",c:"Antiparkinsonien",es:"dyskinésies, hypotension orthostatique, nausées"},
  {n:"Pramipexole",c:"Agoniste dopaminergique",es:"somnolence, troubles du contrôle des impulsions"},
  {n:"Ropinirole",c:"Agoniste dopaminergique",es:"somnolence, nausées"},
  {n:"Rasagiline",c:"IMAO-B (Parkinson)",es:"céphalées, dyskinésies"},
  {n:"Lévétiracétam",c:"Antiépileptique",es:"irritabilité, somnolence, troubles de l'humeur"},
  {n:"Lamotrigine",c:"Antiépileptique",es:"éruption cutanée (risque de Stevens-Johnson)"},
  {n:"Valproate de sodium",c:"Antiépileptique",es:"prise de poids, tremblements, tératogénicité"},
  {n:"Carbamazépine",c:"Antiépileptique",es:"hyponatrémie, somnolence, vertiges"},
  {n:"Topiramate",c:"Antiépileptique",es:"paresthésies, troubles cognitifs, amaigrissement"},
  {n:"Lacosamide",c:"Antiépileptique",es:"sensations vertigineuses, diplopie"},
  {n:"Baclofène",c:"Myorelaxant (spasticité)",es:"somnolence, hypotonie, fatigue"},
  {n:"Sumatriptan",c:"Triptan (migraine)",es:"sensation d'oppression thoracique, fatigue"},
  {n:"Riluzole",c:"Neuroprotecteur (SLA)",es:"asthénie, nausées, élévation des transaminases"},
  {n:"Interféron bêta",c:"Immunomodulateur (SEP)",es:"syndrome pseudo-grippal, réactions locales"},
  /* --- Psychiatrie --- */
  {n:"Sertraline",c:"Antidépresseur ISRS",es:"troubles digestifs, dysfonction sexuelle, hyponatrémie"},
  {n:"Escitalopram",c:"Antidépresseur ISRS",es:"nausées, dysfonction sexuelle, allongement du QT"},
  {n:"Citalopram",c:"Antidépresseur ISRS",es:"nausées, allongement du QT"},
  {n:"Paroxétine",c:"Antidépresseur ISRS",es:"dysfonction sexuelle, syndrome de sevrage"},
  {n:"Fluoxétine",c:"Antidépresseur ISRS",es:"insomnie, nausées, dysfonction sexuelle"},
  {n:"Venlafaxine",c:"Antidépresseur IRSNa",es:"HTA, nausées, sueurs"},
  {n:"Duloxétine",c:"Antidépresseur IRSNa",es:"nausées, sécheresse buccale, insomnie"},
  {n:"Mirtazapine",c:"Antidépresseur (noradrénergique/sérotoninergique)",es:"prise de poids, somnolence"},
  {n:"Amitriptyline",c:"Antidépresseur tricyclique",es:"effets anticholinergiques, somnolence, prise de poids"},
  {n:"Lithium",c:"Thymorégulateur",es:"tremblements, dysthyroïdie, atteinte rénale"},
  {n:"Rispéridone",c:"Antipsychotique (2e génération)",es:"prise de poids, syndrome extrapyramidal, hyperprolactinémie"},
  {n:"Olanzapine",c:"Antipsychotique (2e génération)",es:"prise de poids, syndrome métabolique, sédation"},
  {n:"Aripiprazole",c:"Antipsychotique (2e génération)",es:"akathisie, insomnie, nausées"},
  {n:"Quétiapine",c:"Antipsychotique (2e génération)",es:"sédation, prise de poids, hypotension"},
  {n:"Halopéridol",c:"Antipsychotique (1re génération)",es:"syndrome extrapyramidal, dyskinésies"},
  {n:"Clozapine",c:"Antipsychotique (résistance)",es:"agranulocytose, sédation, hypersialorrhée"},
  {n:"Diazépam",c:"Benzodiazépine",es:"sédation, dépendance, chutes"},
  {n:"Lorazépam",c:"Benzodiazépine",es:"sédation, troubles de la mémoire, dépendance"},
  {n:"Alprazolam",c:"Benzodiazépine",es:"sédation, dépendance, syndrome de sevrage"},
  {n:"Oxazépam",c:"Benzodiazépine",es:"sédation, somnolence, chutes"},
  {n:"Zopiclone",c:"Hypnotique apparenté aux benzodiazépines",es:"somnolence diurne, goût amer, dépendance"},
  {n:"Zolpidem",c:"Hypnotique apparenté aux benzodiazépines",es:"somnolence, troubles du comportement nocturne"},
  {n:"Méthylphénidate",c:"Psychostimulant (TDAH)",es:"anorexie, insomnie, tachycardie"},
  {n:"Mémantine",c:"Anti-démentiel (anti-NMDA)",es:"vertiges, céphalées, constipation"},
  {n:"Donépézil",c:"Anticholinestérasique (démence)",es:"troubles digestifs, bradycardie, crampes"},
  {n:"Rivastigmine",c:"Anticholinestérasique (démence)",es:"nausées, vomissements, anorexie"},
  /* --- Antalgiques / rhumato --- */
  {n:"Paracétamol",c:"Antalgique de palier 1",es:"hépatotoxicité en cas de surdosage"},
  {n:"Ibuprofène",c:"AINS",es:"toxicité digestive, atteinte rénale, HTA"},
  {n:"Diclofénac",c:"AINS",es:"toxicité digestive, risque cardiovasculaire"},
  {n:"Naproxène",c:"AINS",es:"toxicité digestive, rétention hydrosodée"},
  {n:"Kétoprofène",c:"AINS",es:"toxicité digestive, photosensibilité"},
  {n:"Célécoxib",c:"AINS (coxib)",es:"risque cardiovasculaire, HTA"},
  {n:"Tramadol",c:"Antalgique de palier 2 (opioïde faible)",es:"nausées, vertiges, somnolence, dépendance"},
  {n:"Codéine",c:"Antalgique de palier 2 (opioïde faible)",es:"constipation, somnolence"},
  {n:"Morphine",c:"Antalgique de palier 3 (opioïde fort)",es:"constipation, somnolence, dépression respiratoire"},
  {n:"Oxycodone",c:"Antalgique de palier 3 (opioïde fort)",es:"constipation, sédation, dépendance"},
  {n:"Fentanyl",c:"Antalgique de palier 3 (opioïde fort)",es:"constipation, sédation, dépression respiratoire"},
  {n:"Prégabaline",c:"Antalgique des douleurs neuropathiques",es:"somnolence, prise de poids, œdèmes, vertiges"},
  {n:"Gabapentine",c:"Antalgique des douleurs neuropathiques",es:"somnolence, vertiges, œdèmes"},
  {n:"Colchicine",c:"Anti-goutteux",es:"diarrhée, troubles digestifs"},
  {n:"Allopurinol",c:"Hypouricémiant",es:"éruption cutanée, troubles digestifs"},
  {n:"Alendronate",c:"Bisphosphonate (ostéoporose)",es:"œsophagite, troubles digestifs, douleurs osseuses"},
  {n:"Risédronate",c:"Bisphosphonate (ostéoporose)",es:"œsophagite, douleurs musculo-squelettiques"},
  {n:"Dénosumab",c:"Anti-ostéoporotique (anti-RANKL)",es:"hypocalcémie, douleurs, infections"},
  /* --- Digestif / divers --- */
  {n:"Oméprazole",c:"Inhibiteur de la pompe à protons",es:"hypomagnésémie, infections digestives, carence B12"},
  {n:"Ésoméprazole",c:"Inhibiteur de la pompe à protons",es:"céphalées, troubles digestifs"},
  {n:"Pantoprazole",c:"Inhibiteur de la pompe à protons",es:"diarrhée, hypomagnésémie"},
  {n:"Mésalazine",c:"Anti-inflammatoire intestinal (MICI)",es:"troubles digestifs, atteinte rénale (rare)"},
  {n:"Tamoxifène",c:"Hormonothérapie (cancer du sein)",es:"bouffées de chaleur, risque thrombo-embolique"},
  {n:"Ténofovir/emtricitabine",c:"Antirétroviral (VIH)",es:"troubles digestifs, atteinte rénale/osseuse"},
  {n:"Dolutégravir",c:"Antirétroviral (VIH)",es:"insomnie, céphalées, prise de poids"}
];
